version: '3.8'

services:
  app:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2'
      SPRING_DATASOURCE_USERNAME: '3AHrjpqYSshHyUV.root'
      SPRING_DATASOURCE_PASSWORD: 'tSk2pkgMIoM3QbkH'  

      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 20MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 20MB

      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: "caoky.sonha@gmail.com"
      SPRING_MAIL_PASSWORD: "iisrdsbtaljjucag"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    ports:
      - "8080:8080"
