name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Kill existing process on port 80
      run: |
        sudo lsof -t -i:80 | xargs sudo kill -9

    - name: Execute Jar file
      run: |
        sudo java -jar /home/ubuntu/actions-runner/_work/backend/backend/target/api-0.0.1-SNAPSHOT.jar
 
