name: Maven Package

on:
  push:
    branches: 
      - main
  release:
    types: 
      - created

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # ID của repository trong section distributionManagement/repository/id của pom.xml
        settings-path: ${{ github.workspace }} # Đường dẫn đến tệp settings.xml nếu có

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn deploy --file pom.xml --settings ${{ github.workspace }}/.github/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
